		
CREATE DATABASE QLST_TTN
GO
USE QLST_TTN
GO

Create TABLE DANGNHAP
(
	TaiKhoan NVARCHAR(30),
	MatKhau VARCHAR(30)
)
GO
Create TABLE NHANVIEN
(
	MANV VARCHAR(8) PRIMARY KEY NOT NULL,
	TENNV NVARCHAR(50) NOT NULL,
	MAGH VARCHAR(8) REFERENCES GIANHANG(MAGH) ON DELETE CASCADE,
	GIOITINH NVARCHAR(5) CHECK (GIOITINH IN (N'Nam',N'Nữ')),
	NGAYSINH DATE,
	DIENTHOAI VARCHAR(11)
)
GO
Create TABLE KHACHHANG
(
	MAKH VARCHAR(8) PRIMARY KEY NOT NULL,
	TENKH NVARCHAR(50) NOT NULL,
	DIENTHOAI VARCHAR(11)
)
GO
Create TABLE GIANHANG
(
	MAGH VARCHAR(8) PRIMARY KEY NOT NULL,
	TENGH NVARCHAR(50) NOT NULL,
	VITRI NVARCHAR(50)
)
GO
Create TABLE HOADON
(
	MAHD VARCHAR(8) PRIMARY KEY NOT NULL,
	NGAYLAP DATE,
	MANV VARCHAR(8) REFERENCES NHANVIEN(MANV) ON DELETE CASCADE,
	MAKH varchar(8) REFERENCES KHACHHANG(MAKH) ON DELETE CASCADE,

)
GO
Create TABLE LOAIHANGHOA
(
	MALHH VARCHAR(8) PRIMARY KEY NOT NULL,
	TENLHH NVARCHAR(50) NOT NULL,
	MAGH varchar(8) REFERENCES GIANHANG(MAGH) ON DELETE CASCADE,

)
GO

Create TABLE CHITIETLOAIHANG
(
	 PRIMARY KEY(MANCC,MALHH),
	 MANCC VARCHAR(8) REFERENCES NHACUNGCAP(MANCC) ON DELETE CASCADE,
	 MALHH VARCHAR(8) REFERENCES LOAIHANGHOA(MALHH) ON DELETE CASCADE,
	 SOLUONG INT
)
GO
Create TABLE NHACUNGCAP
(
	MANCC VARCHAR(8) PRIMARY KEY NOT NULL,
	TENNCC NVARCHAR(50) NOT NULL,
	DIENTHOAI VARCHAR(11)
)
GO

Create TABLE CHITIETHOADON
(
	 PRIMARY KEY(MAHD,MAHH),
	 MAHD VARCHAR(8) REFERENCES HOADON(MAHD) ON DELETE CASCADE,
	 MAHH VARCHAR(8) REFERENCES HANGHOA(MAHH) ,
	 SOLUONG INT,
	 DONGIA INT,
	 THANHTIEN INT
)
GO

Create TABLE HANGHOA
(
	MAHH VARCHAR(8) PRIMARY KEY NOT NULL,
	TENHH NVARCHAR(50) NOT NULL,
	GIA int,
	NSX Date,
	HSD Date,
	MALHH varchar(8) REFERENCES LOAIHANGHOA(MALHH) ON DELETE CASCADE,
)
GO

